"""empty message

Revision ID: 16a7a4e4692c
Revises: 9ee5be90d86e
Create Date: 2023-10-31 03:27:42.494837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a7a4e4692c'
down_revision = '9ee5be90d86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('customer_email_key', type_='unique')
        batch_op.drop_constraint('customer_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint('customer_phone_key', ['phone'])
        batch_op.create_unique_constraint('customer_email_key', ['email'])

    # ### end Alembic commands ###
