"""empty message

Revision ID: 202e967f7d5e
Revises: 876e3439c44d
Create Date: 2023-10-23 05:15:32.414870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202e967f7d5e'
down_revision = '876e3439c44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
