"""empty message

Revision ID: 217659878215
Revises: 9cdf536f0140
Create Date: 2023-10-18 00:27:29.294052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217659878215'
down_revision = '9cdf536f0140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.String(length=15), nullable=False),
    sa.Column('stock', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=15), nullable=False))
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('nickname')

    op.drop_table('product')
    # ### end Alembic commands ###
