"""empty message

Revision ID: 279b409fbb0e
Revises: 24c26482bc8d
Create Date: 2023-11-13 20:45:54.077530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279b409fbb0e'
down_revision = '24c26482bc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)

    # ### end Alembic commands ###
