"""empty message

Revision ID: 498e4428fc14
Revises: 7934ba4f0a8d
Create Date: 2023-11-21 18:58:04.978080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498e4428fc14'
down_revision = '7934ba4f0a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
