"""empty message

Revision ID: 6155d08987e0
Revises: ef0dcd158337
Create Date: 2023-10-19 00:55:37.025381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6155d08987e0'
down_revision = 'ef0dcd158337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.alter_column('unit_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('unit_cost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('unit_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
