"""empty message

Revision ID: 7934ba4f0a8d
Revises: 279b409fbb0e
Create Date: 2023-11-20 14:09:30.475081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7934ba4f0a8d'
down_revision = '279b409fbb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('banner')

    # ### end Alembic commands ###
