"""empty message

Revision ID: 876e3439c44d
Revises: 974018f2ac9c
Create Date: 2023-10-23 05:14:44.694335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876e3439c44d'
down_revision = '974018f2ac9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
