"""empty message

Revision ID: 974018f2ac9c
Revises: 12e100eef89a
Create Date: 2023-10-23 05:10:45.649977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974018f2ac9c'
down_revision = '12e100eef89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    op.drop_table('subcategory')
    # ### end Alembic commands ###
