"""empty message

Revision ID: 98caaf039023
Revises: b51d7398a36d
Create Date: 2023-10-23 03:56:05.615051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98caaf039023'
down_revision = 'b51d7398a36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('order_payment_method_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'payment', ['payment_id'], ['id'])
        batch_op.drop_column('payment_method_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unit_cost', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_payment_method_id_fkey', 'payment', ['payment_method_id'], ['id'])
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
