"""empty message

Revision ID: b7ee45f0594c
Revises: 9a3021b1db8b
Create Date: 2023-10-29 08:43:54.843300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ee45f0594c'
down_revision = '9a3021b1db8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_sale', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('for_sale')

    # ### end Alembic commands ###
