"""empty message

Revision ID: ef0dcd158337
Revises: effc1589228e
Create Date: 2023-10-19 00:53:50.663604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0dcd158337'
down_revision = 'effc1589228e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('sku')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
