"""empty message

Revision ID: effc1589228e
Revises: 217659878215
Create Date: 2023-10-18 00:29:40.322740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effc1589228e'
down_revision = '217659878215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_category_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_category_key', ['category'])

    # ### end Alembic commands ###
